### ISSUE TITLE
Not receiving votes (likely set up issue)

### ISSUE THREAD

**Issue by spaceclouds42** [DrexHD/Fabric-Votifier#1]
Config files generated, but the server doesn't seem to pick up any votes sent off by any vote site I tried. @Obydux also had the same issue and never managed to figure out. It's likely cause we just don't know how to use the mod, but there really isn't any documentation to go off of :/

**Comment by xXxIshadowxXX** [comment]
i had this problem as well.
have you been able to fix it

**Comment by spaceclouds42** [comment]
I haven't gotten around to testing, but since I have posted this issue, a readme has been made explaining how to use

**Comment by xXxIshadowxXX** [comment]
i see, even with the readme i still can't manage to make it work...
