### ISSUE TITLE
Mod breaks after first incoming connection

### ISSUE THREAD

**Issue by rpetersen27** [DrexHD/Fabric-Votifier#11]
I configured votifier and started to setup the first pages with it. I tested with planet-minecraft and the votifier connection could be successfully established. Nevertheless I saw this error in the console: 

```
[Thread-1/ERROR]: Uncaught exception in thread "Thread-1"
java[7808]: java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
at me.drex.votifier.VoteReceiver.run(VoteReceiver.java:122) ~[fabric-votifier-1.1.3.jar:?]
```

Since then, I couldn't vote or test the votifier from planet minecraft again. 

I am running 1.19.2 with a bunch of performance mods (lithium and stuff), but nothing special.

**Comment by DrexHD** [comment]
Sorry, looks like I never pushed my local changes. An updated build should be available at this [github action](https://github.com/DrexHD/Fabric-Votifier/actions/runs/3275738749) soon!

**Comment by rpetersen27** [comment]
Perfect, that worked. Thanks
