### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by ysefwakil** [DrexHD/Fabric-Votifier#14]
Not sure why this is happening  when I cast my vote:

28.03 23:41:36 [Server] INFO java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
28.03 23:41:36 [Server] INFO at me.drex.votifier.VoteReceiver.run(VoteReceiver.java:122) ~[fabric-votifier-1.1.3.jar:?]

**Comment by DrexHD** [comment]
The [latest release](https://github.com/DrexHD/Fabric-Votifier/releases/tag/v1.1.5) should fix this issue!
