### ISSUE TITLE
mod not following votifier protocol

### ISSUE THREAD

**Issue by arvitus** [DrexHD/Fabric-Votifier#16]
The mod does not fully follow the original votifier protocol which leads to some votes not working.
According to the [protocol documentation](https://github.com/vexsoftware/votifier#protocol-documentation) votifier must respond with `VOTIFIER <version>` but this mod only responds with `VOTIFIER` which causes issues with server lists that expect the version in the response.

**Comment by DrexHD** [comment]
Interesting, if you want to create a quick PR to fix this I will merge it. I have ported https://github.com/NuVotifier/NuVotifier/pull/322 to fabric. Once there is a maven release of that and/or I have some more time to write a proper vote listener for it this project will be discontinued anyways!

**Comment by arvitus** [comment]
Is there a way to get the mod version dynamically or do I have to hard code it?
