### ISSUE TITLE
Incompatibility with Gunpowder

### ISSUE THREAD

**Issue by laceflower** [DrexHD/Fabric-Votifier#2]
Gunpowder will crash on init when installed alongside fabric-votifier. Unfortunately, I can't provide a full crash log as fabric doesn't create crashlogs during initialization.
[Server Log](https://pastebin.com/WuU1m1vE)

**Comment by DrexHD** [comment]
I haven't tested it, but [v1.1.1](https://github.com/DrexHD/Fabric-Votifier/releases/tag/v1.1.1) should work!

**Comment by laceflower** [comment]
Just tested it, server now starts correctly. Thanks for issuing the fix!
