### ISSUE TITLE
Upgrade 

### ISSUE THREAD

**Issue by SuryaRajgor** [DrexHD/Fabric-Votifier#5]
please release update for 1.17.1 and maybe in some days 1.18

**Comment by DrexHD** [comment]
Votifier should be compatible from 1.14 - 1.18!

**Comment by SuryaRajgor** [comment]
no Its crashed the server https://pastebin.com/yw4amk75

**Comment by DrexHD** [comment]
Oh sorry, this has been patched in a previous update. Please make sure to get the latest version (v1.1.3 from [github releases](https://github.com/DrexHD/Fabric-Votifier/releases)).

**Comment by SuryaRajgor** [comment]
Thanks, It's Work Now And One More Question is there any way to give rewards to voters?? like currency items?? (i use gunpowder currency)

like this..

{ "rewards": [ { "type": "item", "name": "minecraft:diamond", "count": 2, "nbt": "{display:{Name:\"Reward\",Lore:[\"Hello @PLAYER@,\",\"This is your\",\"voting reward from\",\"@SERVICE@\"]}}" }, { "type": "command", "command": "gamemode 1 @PLAYER@" }, { "type": "chat", "message": "[{\"text\":\"@PLAYER@\",\"color\":\"dark_aqua\"},{\"text\":\" just voted on \"},{\"text\":\"@SERVICE@\",\"color\":\"dark_aqua\"},{\"text\":\" and received their daily reward! get yours using \"},{\"text\":\"/vote\",\"color\":\"green\"},{\"text\":\" or by clicking \"},{\"text\":\"here\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://minecraft.curseforge.com/projects/293830\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":{\"text\":\"click to vote!\",\"color\":\"aqua\"}}},{\"text\":\"!\"}]", "broadcast": true, "tellraw": true }, { "type": "chat", "message": "Congratulations @PLAYER@!\nYou just earned your daily reward!", "broadcast": true } ] }

**Comment by SuryaRajgor** [comment]
I add this    commands: ['tellraw @a [{"text":"%PLAYER% voted on %SERVICE%","color":"green"}]', '/give %PLAYER% diamond 5',
  scoreboard players add %PLAYER% voted 1]

but not succeed with gunpowder currency

**Comment by DrexHD** [comment]
The command to add balance to a player, according to [Gunpowder Currency's Readme](https://github.com/Gunpowder-MC/GunpowderCurrency/blob/master/README.md) would be `/balance <player> <set/add/remove> <amount>`. To add 10 to the balance of a voting player you should add `/balance %PLAYER% add 10` to your commands.
```
['tellraw @A [{"text":"%PLAYER% voted on %SERVICE%","color":"green"}]', '/give %PLAYER% diamond 5',
'scoreboard players add %PLAYER% voted 1', 'balance %PLAYER% add 10']

**Comment by SuryaRajgor** [comment]
I do but not work its show " A player is required to run this command here " also try adminAdd  %PLAYER% 10 but the same msg
![image](https://user-images.githubusercontent.com/9131487/143763011-c699866f-563f-4887-89e3-5cbf1769a393.png)

Note: tellraw is already @a  my typing mistake and its work fine
