### ISSUE TITLE
A bit of a question

### ISSUE THREAD

**Issue by Sunconure11** [DrexHD/Fabric-Votifier#6]
Are there any listeners on Fabric I can use? So I can incentivize players to vote a bite more?

**Comment by DrexHD** [comment]
There is a simple config, which allows you to run a command when the vote is received.
`tellraw @a [{\"text\":\"%PLAYER% voted on %SERVICE%\",\"color\":\"green\"}]` would broadcast a message that the player voted, in chat.

**Comment by Sunconure11** [comment]
Alright, thanks
