### ISSUE TITLE
Votifier not receiving any votes, despite correct port, IP, and key

### ISSUE THREAD

**Issue by bwil34** [DrexHD/Fabric-Votifier#7]
Can't get this to work, no matter what port I have tried. Triple-checked to make sure the public key matched. No server listing site that I have tried can send a test vote. Any ideas? I'm all out of them.

**Comment by DrexHD** [comment]
Make sure the port you are using is accessible ([www.yougetsignal.com](https://www.yougetsignal.com/tools/open-ports/)). If that is the case, you can use ([mctools.org](https://mctools.org/votifier-tester)) for further testing. If it still doesn't work, please make sure to attach your logs.

**Comment by bwil34** [comment]
[latest.log](https://github.com/DrexHD/Fabric-Votifier/files/8007301/latest.log)
Attached log from recent restart. Says it can't load the votifier config.
Using yougetsignal, no port that I have tried works.

**Comment by DrexHD** [comment]
> Attached log from recent restart. Says it can't load the votifier config.

There seems to be a syntax error in your config file, you can delete the file to regenerate it upon restart.
> Using yougetsignal, no port that I have tried works.

You will need an open port, for outside services to "talk" to that port, to send the vote.

**Comment by bwil34** [comment]
Not sure why it wasn't working before, I suppose it magically fixed itself. Thanks for the responses though!!
