### ISSUE TITLE
Using on a fabric server in a bungeecord proxy network.

### ISSUE THREAD

**Issue by lzyfi** [DrexHD/Fabric-Votifier#8]
The setup is: Waterfall proxy server, paper based servers and one fabric server connecting through fabric-proxy. We are using NuVotifier for the voting.

Is using this mod possible in this setup, and if so, how would one set it up?

**Comment by DrexHD** [comment]
I am not really familiar with votifiers on proxies, but I am pretty sure they use some kind of message forwarding, which is not supported by this simple fabric mod.

**Comment by DrexHD** [comment]
I have been working on [porting NuVotifier to fabric](https://github.com/NuVotifier/NuVotifier/pull/322), which supports proxies plugin message forwarding. If / when this gets merged I will publish a simple vote listener for fabric that can be used with it.

**Comment by DrexHD** [comment]
This is now possible using a different set of mods. Check the readme archive notice for further info!
